language: node_js
node_js:
- '10'
sudo: required
services:
- docker
- mongodb
script:
- npm run test
deploy:
  provider: gae
  project: users-ms
  keyfile: gce.json
  skip_cleanup: true
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_c5342516af6d_key -iv $encrypted_c5342516af6d_iv
  -in gce.json.enc -out gce.json -d
